Vjezba.Web/Controllers/ThreeDController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Vjezba.DAL;
using Vjezba.Model;
using Vjezba.Web.Models;

// https://threejsfundamentals.org/threejs/lessons/threejs-load-obj.html

namespace Vjezba.Web.Controllers
{
    public class ThreeDController : BaseController
    {
        private static string filePathForDB;
        private ThreeDModelDbContext _dbContext;

        public ThreeDController(ThreeDModelDbContext dbContext, UserManager<AppUser> userManager) : base(userManager)
        {
            this._dbContext = dbContext;
        }

        //[AllowAnonymous]
        public IActionResult Index(ThreeDFilterModel filter)
        {
            var ThreeDQuery = this._dbContext.threeD.Include(p => p.objAttachment).ToList();

            return View("Index", model: ThreeDQuery);
        }

        //[Authorize(Roles = "Manager,Admin")]
        public IActionResult Create()
        {
            this.FillDropdownValues();
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Create(ThreeD model)
        {
            if (ModelState.IsValid)
            {
                model.CreatedBy = UserId;              

                OBJAttachment objatt = new OBJAttachment();
                objatt.OBJFilePath = filePathForDB;
                model.objAttachment = objatt;
                
                model.UploadedDateTime = DateTime.Now;

                int categoryid = model.CategoryID;
                model.CategoryID = categoryid;

                this._dbContext.threeD.Add(model);
                this._dbContext.SaveChanges();

                return RedirectToAction(nameof(Index));
            }
            else
            {
                this.FillDropdownValues();
                // modelstate se ponistava tako da prilikom load-a ne prikaze validaciju
                ModelState.Clear();
                return View();
            }
        }

        [Authorize(Roles = "Admin,User")]
        public IActionResult Details(int? id = null)
        {
            var ThreeD = this._dbContext.threeD
                .Include(t => t.objAttachment)
            .FirstOrDefault(p => p.objAttachmentID == id);

            ViewBag.FilePath = ThreeD.objAttachment.OBJFilePath;
            ViewBag.FileComment = ThreeD.Comment;
            ViewBag.FileDateModified = ThreeD.UploadedDateTime;
            return View("_3DModelView");
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult AjaxSearch(ThreeDFilterModel filter)
        {
            var ThreeDQuery = this._dbContext.threeD.Include(p => p.objAttachment)
                .Include(c => c.Category)
                .AsQueryable();

            filter = filter ?? new ThreeDFilterModel();

            if (!string.IsNullOrWhiteSpace(filter.Name))
            {
                ThreeDQuery = ThreeDQuery.Where(p => p.Name.ToLower().Contains(filter.Name.ToLower()));
            }
            if (!string.IsNullOrWhiteSpace(filter.Category))
            {
                ThreeDQuery = ThreeDQuery.Where(p => p.Category.Name.ToLower().Contains(filter.Category.ToLower()));
            }               

            var model = ThreeDQuery.ToList();

            return PartialView("_IndexTable", model: model);
        }

        public void UploadObjFile(IFormFile file)
        {
            var FileDic = @"wwwroot\3DModels";
            var fileName = file.FileName;
            var filePath = Path.Combine(FileDic, fileName);

            filePathForDB = "/3DModels/" + fileName;

            using (FileStream fs = System.IO.File.Create(filePath))
            {
                file.CopyTo(fs);
            }
        }
        private void FillDropdownValues()
        {
            var selectItems = new List<SelectListItem>();

            var listItem = new SelectListItem();
            listItem.Text = "- 3D/Category -";
            listItem.Value = "";
            selectItems.Add(listItem);

            foreach (var category in this._dbContext.threeDCategoryes)
            {
                listItem = new SelectListItem(category.Name, category.ID.ToString());
                selectItems.Add(listItem);      
            }
            ViewBag.PossibleCategoryes = selectItems;
        }
    }
}

Vjezba.Web/Views/Shared/3DModelView.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset=UTF-8 />
    @* <link rel="stylesheet" type="text/css" href="styles.css" />*@
</head>
<body>
    <script src="~/js/three.js"></script>
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/three.js/104/three.js"></script>*@
    <script src="~/js/OrbitControls.js"></script>
    <script src="~/js/OBJLoader.js"></script>

    @*<script src="https://unpkg.com/three@0.87.1/build/three.js"></script>
        <script src="https://unpkg.com/three@0.87.1/examples/js/controls/OrbitControls.js"></script>
        <script src="https://unpkg.com/three@0.87.1/examples/js/loaders/GLTFLoader.js"></script>*@

    <canvas id="c" style=" width: 100%; height: 100%; display: block;"></canvas>

    <script>

        function main() {
            const canvas = document.querySelector('#c');
            const renderer = new THREE.WebGLRenderer({ canvas });

            const fov = 45;
            const aspect = 2;  // the canvas default
            const near = 0.1;
            const far = 100;
            const camera = new THREE.PerspectiveCamera(fov, aspect, near, far);
            camera.position.set(0, 10, 20);

            const controls = new THREE.OrbitControls(camera, canvas);
            controls.target.set(0, 5, 0);
            controls.update();

            const scene = new THREE.Scene();
            scene.background = new THREE.Color('black');

            {
                const planeSize = 40;

                const loader = new THREE.TextureLoader();
                const texture = loader.load('https://threejsfundamentals.org/threejs/resources/images/checker.png');
                texture.wrapS = THREE.RepeatWrapping;
                texture.wrapT = THREE.RepeatWrapping;
                texture.magFilter = THREE.NearestFilter;
                const repeats = planeSize / 2;
                texture.repeat.set(repeats, repeats);

                const planeGeo = new THREE.PlaneGeometry(planeSize, planeSize);
                const planeMat = new THREE.MeshPhongMaterial({
                    map: texture,
                    side: THREE.DoubleSide,
                });
                const mesh = new THREE.Mesh(planeGeo, planeMat);
                mesh.rotation.x = Math.PI * -.5;
                scene.add(mesh);
            }

            {
                const skyColor = 0xB1E1FF;  // light blue
                const groundColor = 0xB97A20;  // brownish orange
                const intensity = 1;
                const light = new THREE.HemisphereLight(skyColor, groundColor, intensity);
                scene.add(light);
            }

            {
                const color = 0xFFFFFF;
                const intensity = 1;
                const light = new THREE.DirectionalLight(color, intensity);
                light.position.set(5, 10, 2);
                scene.add(light);
                scene.add(light.target);
            }

            var objLoader = new THREE.OBJLoader();
            var material = new THREE.MeshBasicMaterial({ color: 'blue', side: THREE.DoubleSide });
            objLoader.load('3DModels/TVZ.obj', function (obj) {
                obj.traverse(function (child) {

                    if (child instanceof THREE.Mesh) {
                        child.material = material;
                    }

                });
                scene.add(obj);
            });

            //{
            //    const mtlLoader = new THREE.MTLLoader();
            //    mtlLoader.load('3DModels/Test.obj', (mtl) => {
            //        mtl.preload();
            //        const objLoader = new THREE.OBJLoader();
            //        objLoader.setMaterials(mtl);
            //        objLoader.load('3DModels/Test.obj', (root) => {
            //            scene.add(root);
            //        });
            //    });
            //}

            function resizeRendererToDisplaySize(renderer) {
                const canvas = renderer.domElement;
                const width = canvas.clientWidth;
                const height = canvas.clientHeight;
                const needResize = canvas.width !== width || canvas.height !== height;
                if (needResize) {
                    renderer.setSize(width, height, false);
                }
                return needResize;
            }

            function render() {

                if (resizeRendererToDisplaySize(renderer)) {
                    const canvas = renderer.domElement;
                    camera.aspect = canvas.clientWidth / canvas.clientHeight;
                    camera.updateProjectionMatrix();
                }

                renderer.render(scene, camera);

                requestAnimationFrame(render);
            }

            requestAnimationFrame(render);
        }

        main();

    </script>

</body>
</html>

Vjezba.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>THREE-D</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/dropzone/dist/basic.css" />
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">THREE-D</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ThreeD" asp-action="Index">3D models list</a>
                        </li>

                        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Client" asp-action="Index">Popis klijenata</a>
        </li>*@

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Vjezba.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <!--<script src="~/js/three.js"></script>
    <script src="~/js/GLTFLoader.js"></script>--> @*asp-append-version="true"*@
    <!--<script src="~/js/OrbitControls.js"></script>-->

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <partial name="_ValidationScriptsPartial" />
    <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>